version: "3"

services:
  lamp:
    build:
      context: ./bin/lamp
    container_name: 'lamp'
    restart: 'no'
    ports:
      - "127.0.0.1:80:80" # open only localhost for all host replace 127.0.0.1 for 0.0.0.0
    links:
      - mysql
#      - postgres
    volumes:
      - ${DOCUMENT_ROOT}:/proyectos
      - ${HTML_DIR}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/etc/apache2/logs/apache2/
    env_file:
      - ./.env    
  mysql:
    build: ./bin/mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'mysql'
    restart: 'no'
    ports:
      - "3600:3600"
    volumes:
      - ${DOCUMENT_ROOT}:/proyectos
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - ${MYSQL_CONFIG_DIR}:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#  postgres:
#    build: ./bin/postgres
#    container_name: 'postgres'
#    restart: 'always'
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - ${DOCUMENT_ROOT}:/proyectos
#      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
#      - ${POSTGRES_LOG_DIR}:/var/log/postgres
